# All ML Regression Analyses using 13 Models

In [3]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Activate the Inline mod
%matplotlib inline

# To ignore/hide the warnings
import warnings
warnings.filterwarnings("ignore")

## Read Data

In [6]:
df = pd.read_excel("sample_data.xlsx")
df.head(3)

,Car_Name,Car_Age,Target,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,11,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,7,7.25,9.85,6900,Petrol,Dealer,Manual,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Car_Age        301 non-null    int64
 2   Target         301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

## Unique Values

In [14]:
# For getting detailed information about the dataset;

def get_unique_values(df):
    
    output_data = []

    for col in df.columns:

        # If the number of unique values in the column is less than or equal to 5
        if df.loc[:, col].nunique() <= 5:
            # Get the unique values in the column
            unique_values = df.loc[:, col].unique()
            # Append the column name, number of unique values, unique values, and data type to the output data
            output_data.append([col, df.loc[:, col].nunique(), unique_values, df.loc[:, col].dtype])
        else:
            # Otherwise, append only the column name, number of unique values, and data type to the output data
            output_data.append([col, df.loc[:, col].nunique(),"-", df.loc[:, col].dtype])

    output_df = pd.DataFrame(output_data, columns=['Column Name', 'Number of Unique Values', ' Unique Values ', 'Data Type'])

    return output_df

get_unique_values(df)

     Column Name  Number of Unique Values         Unique Values  Data Type
0       Car_Name                       98                      -    object
1        Car_Age                       16                      -     int64
2         Target                      156                      -   float64
3  Present_Price                      147                      -   float64
4     Kms_Driven                      206                      -     int64
5      Fuel_Type                        3  [Petrol, Diesel, CNG]    object
6    Seller_Type                        2   [Dealer, Individual]    object
7   Transmission                        2    [Manual, Automatic]    object
8          Owner                        3              [0, 1, 3]     int64

* There are 98 category at "Car_Name". We can not apply dummy encoding  to this column. 

* Let's drop it.

## Drop

In [17]:
df = df.drop('Car_Name', axis=1)
df.head(2)

,Car_Age,Target,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,11,4.75,9.54,43000,Diesel,Dealer,Manual,0

## Encoding

* We should apply dummy encoding at regression analyses.

In [1]:
# expecially in regression we can use dummy encoding

In [18]:
# List the categorical columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

# Apply dummy encoding with drop_first=True for the categorical columns (Also, original columns were dropped)
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df.head(2)

,Car_Age,Target,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,10,3.35,5.59,27000,0,0,1,0,1
1,11,4.75,9.54,43000,0,1,0,0,1

## Handling with null values

In [8]:
df.isna().sum()

Car_Name         0
Car_Age          0
Target           0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64


* We don't need this code now. 

* I put here in case of you will need in future.

In [9]:
# Fill null values in categorical columns with mode
for col in df.select_dtypes(include=['object', 'category']):
    df[col].fillna(df[col].mode()[0], inplace=True)

In [10]:
# Fill null values in numerical columns with mean
for col in df.select_dtypes(include=['number']):
    df[col].fillna(df[col].mean(), inplace=True)

## Labelling

In [19]:
X = df.drop(columns ="Target")
y = df["Target"]

## Split as Train & Test

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

## Scalling

Although scaling is not necessary for tree-based algorithms; it is important for Linear Regression, Regulation, KNN and SVM. 

Additionally, we can use scaled data in tree-based algorithms, too. Sometimes, this can improve our models' performance (speed).

**Machine Learning Methods That Require Scaling**

Scaling is particularly important for algorithms that are based on distance calculations or gradient-based optimization. However, it is not necessary for all machine learning methods. Below is a summary of when scaling is required and when it is not.

**Algorithms That Require Scaling**

These algorithms are sensitive to the scale of features, so scaling is essential:

**K-Nearest Neighbors (KNN):** KNN relies on distance metrics (like Euclidean or Manhattan). Without scaling, features with larger ranges will dominate the distance calculation, leading to biased predictions. Use either StandardScaler or MinMaxScaler.

**Support Vector Machines (SVM):** SVM constructs hyperplanes based on the distance between data points and the decision boundary. Without scaling, it can be difficult to find the optimal hyperplane.

**Logistic Regression:** Logistic regression uses gradient descent for optimization. Different scales across features can slow down or skew the optimization process, affecting model performance.

**Neural Networks (MLP - Multi-Layer Perceptron):** Neural networks update weights using gradient-based optimization. Large differences in feature scales can cause slower convergence and poor performance.

**Principal Component Analysis (PCA):** PCA is based on capturing the variance in the data. Features with larger ranges will contribute more to the variance, overshadowing others, making scaling essential.

**Gradient Boosting Algorithms (XGBoost, LightGBM, CatBoost):** Although tree-based, these algorithms use gradient-based optimization internally. While generally robust, scaling can improve performance and convergence speed.

**Linear Regression:** For linear regression, particularly with regularization techniques like Ridge or Lasso, scaling is necessary. Regularization is sensitive to the magnitude of coefficients, so scaling ensures all features are treated equally.



**-------------Algorithms That Do Not Require Scaling--------------**

These methods are not sensitive to feature scales and therefore do not need scaling:

**Decision Trees (CART, Random Forest):** Decision trees use threshold-based splits, so the scale of features does not affect the way the tree is constructed. Scaling has no impact on the model’s performance.

**Bagging Methods (Random Forest, Bagging):** Since bagging techniques often rely on decision trees, they also do not require scaling. 

**Naive Bayes:** Naive Bayes models work with probabilities based on feature values, which are independent of scale, so no scaling is necessary.

**Tree-based Gradient Boosting Algorithms:** Tree-based methods like XGBoost, LightGBM, and CatBoost use decision trees, which do not rely on feature scaling. However, scaling may help for the optimization part of these models.

**K-Means Clustering:** Although not strictly necessary, K-means uses distance calculations and can benefit from scaling to ensure all features are treated equally.

* BUT, if you use scaled data at these models, it will not cause a problem. 



**------Summary-----**:

**Algorithms that require scaling:** KNN, SVM, Logistic Regression, Neural Networks, PCA, Gradient Boosting, Linear Regression.
**Algorithms that do not require scaling:** Decision Trees, Random Forest, Naive Bayes, Bagging methods.

In general, distance-based and gradient-based methods require scaling, while tree-based methods do not. However, if you are using a pipeline that involves multiple models, it may be useful to scale all features for consistency across the pipeline.

In [21]:
X_train.head(2)

,Car_Age,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
184,16,0.75,26000,1,0,1,1,1
132,7,0.95,3500,0,0,1,1,1

In [28]:
# Initialize the MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

In [ ]:
# when we have dummy data , its good to use minmax scaler

In [29]:
"""
NOT necessary for you!!!

# Convert the scaled NumPy array back into a pandas DataFrame
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)

# Now you can use .head() on the DataFrame
print(X_train_scaled.head(2))"""

    Car_Age  Present_Price  Kms_Driven     Owner  Fuel_Type_Diesel  \
0  0.642857       0.004660    0.051051  0.333333               0.0
1  0.000000       0.006827    0.006006  0.000000               0.0

   Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual
0               1.0                     1.0                  1.0
1               1.0                     1.0                  1.0

In [30]:
X_test.head(2)

,Car_Age,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
177,8,0.57,24000,0,0,1,1,0
289,8,13.60,10980,0,0,1,0,1

In [3]:
# in training data we fit transform 
# but in test data we only transform 

# to prevent data leakage problem 
# Data leakage is when a model accidentally uses information
# from future or test data during training, causing it to appear more accurate than it actually is.

In [31]:
# Transform the scaler on the test data
X_test_scaled = scaler.transform(X_test)

In [32]:
"""
NOT necessary for you!!!

# Convert the scaled NumPy array back into a pandas DataFrame
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

# Now you can use .head() on the DataFrame
print(X_test_scaled.head(2))"""

    Car_Age  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  0.071429       0.002709    0.047047    0.0               0.0
1  0.071429       0.143910    0.020981    0.0               0.0

   Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual
0               1.0                     1.0                  0.0
1               1.0                     0.0                  1.0

## Modelling

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

In [47]:
# Fit the models
linear = LinearRegression().fit(X_train_scaled, y_train)
ridge=Ridge().fit(X_train_scaled, y_train)
lasso=Lasso().fit(X_train_scaled, y_train)
enet=ElasticNet().fit(X_train_scaled, y_train)
knn=KNeighborsRegressor().fit(X_train_scaled, y_train)
ada=AdaBoostRegressor().fit(X_train_scaled, y_train)
svm=SVR().fit(X_train_scaled, y_train)
mlpc=MLPRegressor().fit(X_train_scaled, y_train) # Multilayer perceptron. ANN model
dtc=DecisionTreeRegressor().fit(X_train_scaled, y_train)
rf=RandomForestRegressor().fit(X_train_scaled, y_train)
xgb=XGBRegressor().fit(X_train_scaled, y_train)
gbm=GradientBoostingRegressor().fit(X_train_scaled, y_train)
lgb=LGBMRegressor().fit(X_train_scaled, y_train) # LightGBM
catbost=CatBoostRegressor().fit(X_train_scaled, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 240, number of used features: 7
[LightGBM] [Info] Start training from score 4.642292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Learning rate set to 0.032678
0:	learn: 5.0363211	total: 1.89ms	remaining: 1.89s
1:	learn: 4.9464546	total: 6.26ms	remaining: 3.12s
2:	learn: 4.8504633	total: 7.79ms	remaining: 2.59s
3:	learn: 4.7574203	total: 9.08ms	remaining: 2.26s
4:	learn: 4.6638347	total: 10.4ms	remaining: 2.07s
5:	learn: 4.5824986	total: 11.8ms	remaining: 1.96s
6:	learn: 4.5180984	total: 12.7ms	remaining: 1.8s
7:	learn: 4.4367646	total: 14ms	remaining: 1.73s
8:	learn: 4.3558074	total: 14.6ms	remaining: 1.61s
9:	learn: 4.2785412	total: 16ms	remaining: 1.58s
10:	learn: 4.2140923	total: 17.3ms	remaining: 1.56s
11:	learn: 4.1565100	total: 18.4ms	remaining: 1.51s
12:	learn: 4.0725655	total: 19.1ms	remaining: 1.45s
13:	learn: 4.0061777	total: 20.2ms	remaining: 1.42s
14:	learn: 3.9433616	total: 21.5ms	remaining: 1.41s
15:	learn: 3.8871514	total: 22.9ms	remaining: 1.41s
16:	learn: 3.8274795	total: 24.2ms	remaining: 1.4s
17:	learn: 3.7576466	total: 25.4ms	remaining: 1.39s
18:	learn: 3.6969935	total: 26.6ms	remaining: 1.37s
19:	learn: 3.6327087	total: 28ms	remaining: 1.37s
20:	learn: 3.5803173	total: 29.4ms	remaining: 1.37s
21:	learn: 3.5218971	total: 30.6ms	remaining: 1.36s
22:	learn: 3.4719602	total: 31.5ms	remaining: 1.34s
23:	learn: 3.4145411	total: 31.9ms	remaining: 1.3s
24:	learn: 3.3581036	total: 33.2ms	remaining: 1.29s
25:	learn: 3.3107136	total: 33.7ms	remaining: 1.26s
26:	learn: 3.2585757	total: 34.5ms	remaining: 1.25s
27:	learn: 3.2057576	total: 35.8ms	remaining: 1.24s
28:	learn: 3.1553921	total: 37.1ms	remaining: 1.24s
29:	learn: 3.1079639	total: 38.4ms	remaining: 1.24s
30:	learn: 3.0599457	total: 39.6ms	remaining: 1.24s
31:	learn: 3.0218892	total: 41ms	remaining: 1.24s
32:	learn: 2.9732001	total: 41.6ms	remaining: 1.22s
33:	learn: 2.9254719	total: 42.9ms	remaining: 1.22s
34:	learn: 2.8870990	total: 44.2ms	remaining: 1.22s
35:	learn: 2.8480252	total: 45.4ms	remaining: 1.22s
36:	learn: 2.8137959	total: 46.7ms	remaining: 1.22s
37:	learn: 2.7722276	total: 48ms	remaining: 1.21s
38:	learn: 2.7270772	total: 49ms	remaining: 1.21s
39:	learn: 2.6888490	total: 49.8ms	remaining: 1.19s
40:	learn: 2.6565462	total: 51ms	remaining: 1.19s
41:	learn: 2.6296105	total: 52.4ms	remaining: 1.19s
42:	learn: 2.5974358	total: 53.8ms	remaining: 1.2s
43:	learn: 2.5601171	total: 54.7ms	remaining: 1.19s
44:	learn: 2.5259272	total: 55.9ms	remaining: 1.19s
45:	learn: 2.4901224	total: 57.2ms	remaining: 1.19s
46:	learn: 2.4514312	total: 58.4ms	remaining: 1.18s
47:	learn: 2.4181403	total: 59.7ms	remaining: 1.18s
48:	learn: 2.3819021	total: 60.9ms	remaining: 1.18s
49:	learn: 2.3575729	total: 62.2ms	remaining: 1.18s
50:	learn: 2.3240535	total: 63.5ms	remaining: 1.18s
51:	learn: 2.2980593	total: 64.2ms	remaining: 1.17s
52:	learn: 2.2812076	total: 65.8ms	remaining: 1.18s
53:	learn: 2.2542780	total: 67.3ms	remaining: 1.18s
54:	learn: 2.2311201	total: 68.5ms	remaining: 1.18s
55:	learn: 2.2032300	total: 69.4ms	remaining: 1.17s
56:	learn: 2.1757357	total: 70.8ms	remaining: 1.17s
57:	learn: 2.1522460	total: 72ms	remaining: 1.17s
58:	learn: 2.1240298	total: 73ms	remaining: 1.16s
59:	learn: 2.1006098	total: 74.4ms	remaining: 1.17s
60:	learn: 2.0775219	total: 76.1ms	remaining: 1.17s
61:	learn: 2.0560396	total: 77.1ms	remaining: 1.17s
62:	learn: 2.0342403	total: 78.6ms	remaining: 1.17s
63:	learn: 2.0108794	total: 79.5ms	remaining: 1.16s
64:	learn: 1.9893154	total: 80.7ms	remaining: 1.16s
65:	learn: 1.9649483	total: 81.7ms	remaining: 1.16s
66:	learn: 1.9448439	total: 83.2ms	remaining: 1.16s
67:	learn: 1.9360051	total: 84.7ms	remaining: 1.16s
68:	learn: 1.9231154	total: 85.3ms	remaining: 1.15s
69:	learn: 1.9010385	total: 86.8ms	remaining: 1.15s
70:	learn: 1.8774580	total: 88.2ms	remaining: 1.15s
71:	learn: 1.8562347	total: 89.8ms	remaining: 1.16s
72:	learn: 1.8354400	total: 90.9ms	remaining: 1.15s
73:	learn: 1.8151220	total: 92.2ms	remaining: 1.15s
74:	learn: 1.7939045	total: 93.9ms	remaining: 1.16s
75:	learn: 1.7732111	total: 94.7ms	remaining: 1.15s
76:	learn: 1.7565936	total: 95.6ms	remaining: 1.15s
77:	learn: 1.7358975	total: 96.6ms	remaining: 1.14s
78:	learn: 1.7182656	total: 97.7ms	remaining: 1.14s
79:	learn: 1.7012072	total: 99ms	remaining: 1.14s
80:	learn: 1.6896086	total: 100ms	remaining: 1.14s
81:	learn: 1.6744051	total: 102ms	remaining: 1.14s
82:	learn: 1.6545530	total: 103ms	remaining: 1.14s
83:	learn: 1.6354601	total: 105ms	remaining: 1.14s
84:	learn: 1.6196862	total: 105ms	remaining: 1.14s
85:	learn: 1.6021684	total: 107ms	remaining: 1.13s
86:	learn: 1.5894936	total: 108ms	remaining: 1.14s
87:	learn: 1.5743762	total: 109ms	remaining: 1.13s
88:	learn: 1.5593989	total: 110ms	remaining: 1.13s
89:	learn: 1.5478470	total: 111ms	remaining: 1.12s
90:	learn: 1.5352654	total: 112ms	remaining: 1.12s
91:	learn: 1.5183234	total: 113ms	remaining: 1.12s
92:	learn: 1.5049196	total: 115ms	remaining: 1.12s
93:	learn: 1.4926060	total: 116ms	remaining: 1.12s
94:	learn: 1.4770643	total: 117ms	remaining: 1.12s
95:	learn: 1.4709457	total: 118ms	remaining: 1.11s
96:	learn: 1.4600587	total: 119ms	remaining: 1.1s
97:	learn: 1.4448080	total: 120ms	remaining: 1.1s
98:	learn: 1.4315742	total: 120ms	remaining: 1.09s
99:	learn: 1.4204261	total: 122ms	remaining: 1.1s

100:	learn: 1.4148402	total: 123ms	remaining: 1.09s
101:	learn: 1.4035382	total: 124ms	remaining: 1.09s
102:	learn: 1.3896695	total: 125ms	remaining: 1.09s
103:	learn: 1.3788734	total: 126ms	remaining: 1.09s
104:	learn: 1.3698316	total: 127ms	remaining: 1.08s
105:	learn: 1.3585003	total: 128ms	remaining: 1.08s
106:	learn: 1.3530320	total: 129ms	remaining: 1.08s
107:	learn: 1.3415801	total: 130ms	remaining: 1.07s
108:	learn: 1.3286521	total: 131ms	remaining: 1.07s
109:	learn: 1.3169189	total: 133ms	remaining: 1.07s
110:	learn: 1.3070445	total: 134ms	remaining: 1.08s
111:	learn: 1.2981346	total: 136ms	remaining: 1.08s
112:	learn: 1.2905916	total: 137ms	remaining: 1.08s
113:	learn: 1.2814684	total: 138ms	remaining: 1.07s
114:	learn: 1.2739813	total: 139ms	remaining: 1.07s
115:	learn: 1.2636211	total: 140ms	remaining: 1.07s
116:	learn: 1.2545160	total: 142ms	remaining: 1.07s
117:	learn: 1.2441649	total: 144ms	remaining: 1.07s
118:	learn: 1.2359286	total: 145ms	remaining: 1.07s
119:	learn: 1.2314279	total: 145ms	remaining: 1.06s
120:	learn: 1.2220253	total: 146ms	remaining: 1.06s
121:	learn: 1.2108870	total: 147ms	remaining: 1.06s
122:	learn: 1.1996832	total: 148ms	remaining: 1.06s
123:	learn: 1.1901232	total: 149ms	remaining: 1.05s
124:	learn: 1.1838615	total: 150ms	remaining: 1.05s
125:	learn: 1.1755885	total: 151ms	remaining: 1.05s
126:	learn: 1.1679587	total: 153ms	remaining: 1.05s
127:	learn: 1.1598879	total: 154ms	remaining: 1.04s
128:	learn: 1.1513700	total: 154ms	remaining: 1.04s
129:	learn: 1.1415702	total: 156ms	remaining: 1.04s
130:	learn: 1.1332409	total: 157ms	remaining: 1.04s
131:	learn: 1.1217798	total: 159ms	remaining: 1.04s
132:	learn: 1.1114338	total: 160ms	remaining: 1.04s
133:	learn: 1.1030269	total: 162ms	remaining: 1.04s
134:	learn: 1.0949837	total: 163ms	remaining: 1.04s
135:	learn: 1.0841226	total: 164ms	remaining: 1.04s
136:	learn: 1.0761677	total: 166ms	remaining: 1.04s
137:	learn: 1.0688884	total: 167ms	remaining: 1.04s
138:	learn: 1.0622985	total: 168ms	remaining: 1.04s
139:	learn: 1.0589986	total: 169ms	remaining: 1.04s
140:	learn: 1.0539146	total: 170ms	remaining: 1.03s
141:	learn: 1.0463324	total: 171ms	remaining: 1.03s
142:	learn: 1.0401315	total: 173ms	remaining: 1.03s
143:	learn: 1.0296713	total: 174ms	remaining: 1.04s
144:	learn: 1.0208494	total: 176ms	remaining: 1.04s
145:	learn: 1.0140329	total: 178ms	remaining: 1.04s
146:	learn: 1.0093480	total: 178ms	remaining: 1.03s
147:	learn: 0.9997288	total: 180ms	remaining: 1.03s
148:	learn: 0.9937577	total: 181ms	remaining: 1.04s
149:	learn: 0.9885975	total: 183ms	remaining: 1.04s
150:	learn: 0.9828373	total: 185ms	remaining: 1.04s
151:	learn: 0.9773468	total: 187ms	remaining: 1.04s
152:	learn: 0.9685859	total: 188ms	remaining: 1.04s
153:	learn: 0.9628666	total: 190ms	remaining: 1.04s
154:	learn: 0.9565221	total: 192ms	remaining: 1.04s
155:	learn: 0.9519688	total: 193ms	remaining: 1.05s
156:	learn: 0.9478403	total: 195ms	remaining: 1.05s
157:	learn: 0.9450240	total: 197ms	remaining: 1.05s
158:	learn: 0.9408845	total: 198ms	remaining: 1.05s
159:	learn: 0.9370062	total: 200ms	remaining: 1.05s
160:	learn: 0.9330414	total: 200ms	remaining: 1.04s
161:	learn: 0.9293863	total: 201ms	remaining: 1.04s
162:	learn: 0.9227950	total: 202ms	remaining: 1.04s
163:	learn: 0.9192717	total: 203ms	remaining: 1.03s
164:	learn: 0.9130464	total: 204ms	remaining: 1.03s
165:	learn: 0.9077341	total: 206ms	remaining: 1.03s
166:	learn: 0.9028402	total: 208ms	remaining: 1.04s
167:	learn: 0.9003746	total: 210ms	remaining: 1.04s
168:	learn: 0.8949899	total: 211ms	remaining: 1.04s
169:	learn: 0.8917823	total: 213ms	remaining: 1.04s
170:	learn: 0.8868199	total: 214ms	remaining: 1.04s
171:	learn: 0.8822043	total: 215ms	remaining: 1.03s
172:	learn: 0.8747884	total: 217ms	remaining: 1.04s
173:	learn: 0.8701289	total: 219ms	remaining: 1.04s
174:	learn: 0.8646774	total: 220ms	remaining: 1.04s
175:	learn: 0.8605736	total: 222ms	remaining: 1.04s
176:	learn: 0.8571584	total: 224ms	remaining: 1.04s
177:	learn: 0.8493646	total: 225ms	remaining: 1.04s
178:	learn: 0.8424759	total: 227ms	remaining: 1.04s
179:	learn: 0.8382983	total: 229ms	remaining: 1.04s
180:	learn: 0.8363557	total: 231ms	remaining: 1.04s
181:	learn: 0.8322413	total: 233ms	remaining: 1.05s
182:	learn: 0.8288020	total: 235ms	remaining: 1.05s
183:	learn: 0.8223780	total: 236ms	remaining: 1.05s
184:	learn: 0.8175851	total: 238ms	remaining: 1.05s
185:	learn: 0.8142782	total: 240ms	remaining: 1.05s
186:	learn: 0.8095719	total: 242ms	remaining: 1.05s
187:	learn: 0.8036275	total: 243ms	remaining: 1.05s
188:	learn: 0.7984373	total: 244ms	remaining: 1.05s
189:	learn: 0.7941280	total: 246ms	remaining: 1.05s
190:	learn: 0.7913284	total: 248ms	remaining: 1.05s
191:	learn: 0.7855310	total: 250ms	remaining: 1.05s
192:	learn: 0.7824787	total: 252ms	remaining: 1.05s
193:	learn: 0.7776473	total: 254ms	remaining: 1.05s
194:	learn: 0.7748332	total: 256ms	remaining: 1.06s
195:	learn: 0.7732702	total: 257ms	remaining: 1.05s
196:	learn: 0.7713978	total: 258ms	remaining: 1.05s
197:	learn: 0.7656287	total: 261ms	remaining: 1.06s
198:	learn: 0.7617288	total: 264ms	remaining: 1.06s
199:	learn: 0.7580772	total: 266ms	remaining: 1.06s
200:	learn: 0.7554422	total: 269ms	remaining: 1.07s
201:	learn: 0.7539491	total: 271ms	remaining: 1.07s
202:	learn: 0.7507169	total: 272ms	remaining: 1.07s
203:	learn: 0.7478094	total: 273ms	remaining: 1.07s
204:	learn: 0.7451429	total: 275ms	remaining: 1.07s
205:	learn: 0.7431151	total: 276ms	remaining: 1.06s
206:	learn: 0.7381873	total: 278ms	remaining: 1.06s
207:	learn: 0.7314748	total: 280ms	remaining: 1.07s
208:	learn: 0.7283241	total: 282ms	remaining: 1.07s
209:	learn: 0.7232351	total: 285ms	remaining: 1.07s
210:	learn: 0.7200045	total: 285ms	remaining: 1.07s
211:	learn: 0.7171981	total: 286ms	remaining: 1.06s
212:	learn: 0.7159563	total: 288ms	remaining: 1.06s
213:	learn: 0.7100479	total: 290ms	remaining: 1.06s
214:	learn: 0.7068259	total: 292ms	remaining: 1.07s
215:	learn: 0.7056558	total: 294ms	remaining: 1.07s
216:	learn: 0.7026812	total: 296ms	remaining: 1.07s
217:	learn: 0.7014065	total: 298ms	remaining: 1.07s
218:	learn: 0.6973265	total: 299ms	remaining: 1.07s
219:	learn: 0.6919483	total: 301ms	remaining: 1.06s
220:	learn: 0.6908757	total: 302ms	remaining: 1.06s
221:	learn: 0.6875331	total: 304ms	remaining: 1.06s
222:	learn: 0.6851818	total: 305ms	remaining: 1.06s
223:	learn: 0.6819277	total: 308ms	remaining: 1.07s
224:	learn: 0.6776168	total: 310ms	remaining: 1.07s
225:	learn: 0.6765832	total: 313ms	remaining: 1.07s
226:	learn: 0.6752502	total: 314ms	remaining: 1.07s
227:	learn: 0.6724206	total: 316ms	remaining: 1.07s
228:	learn: 0.6713435	total: 318ms	remaining: 1.07s
229:	learn: 0.6668651	total: 320ms	remaining: 1.07s
230:	learn: 0.6642292	total: 322ms	remaining: 1.07s
231:	learn: 0.6595015	total: 323ms	remaining: 1.07s
232:	learn: 0.6567907	total: 323ms	remaining: 1.06s
233:	learn: 0.6558365	total: 324ms	remaining: 1.06s
234:	learn: 0.6509705	total: 326ms	remaining: 1.06s
235:	learn: 0.6489040	total: 327ms	remaining: 1.06s
236:	learn: 0.6452671	total: 328ms	remaining: 1.06s
237:	learn: 0.6442008	total: 331ms	remaining: 1.06s
238:	learn: 0.6410257	total: 333ms	remaining: 1.06s
239:	learn: 0.6392312	total: 335ms	remaining: 1.06s
240:	learn: 0.6371002	total: 337ms	remaining: 1.06s
241:	learn: 0.6345829	total: 338ms	remaining: 1.06s
242:	learn: 0.6313769	total: 340ms	remaining: 1.06s
243:	learn: 0.6294484	total: 342ms	remaining: 1.06s
244:	learn: 0.6278124	total: 344ms	remaining: 1.06s
245:	learn: 0.6269297	total: 346ms	remaining: 1.06s
246:	learn: 0.6243230	total: 348ms	remaining: 1.06s
247:	learn: 0.6229466	total: 350ms	remaining: 1.06s
248:	learn: 0.6217144	total: 351ms	remaining: 1.06s
249:	learn: 0.6177525	total: 352ms	remaining: 1.06s
250:	learn: 0.6165875	total: 354ms	remaining: 1.06s
251:	learn: 0.6123314	total: 357ms	remaining: 1.06s
252:	learn: 0.6108643	total: 359ms	remaining: 1.06s
253:	learn: 0.6096542	total: 360ms	remaining: 1.06s
254:	learn: 0.6083032	total: 361ms	remaining: 1.05s
255:	learn: 0.6066685	total: 363ms	remaining: 1.05s
256:	learn: 0.6059921	total: 363ms	remaining: 1.05s
257:	learn: 0.6025504	total: 365ms	remaining: 1.05s
258:	learn: 0.5993160	total: 366ms	remaining: 1.05s
259:	learn: 0.5979362	total: 367ms	remaining: 1.04s
260:	learn: 0.5966329	total: 368ms	remaining: 1.04s
261:	learn: 0.5954054	total: 371ms	remaining: 1.04s
262:	learn: 0.5926975	total: 372ms	remaining: 1.04s
263:	learn: 0.5917037	total: 375ms	remaining: 1.04s
264:	learn: 0.5904606	total: 377ms	remaining: 1.04s
265:	learn: 0.5898078	total: 378ms	remaining: 1.04s
266:	learn: 0.5888695	total: 380ms	remaining: 1.04s
267:	learn: 0.5877728	total: 381ms	remaining: 1.04s
268:	learn: 0.5842917	total: 382ms	remaining: 1.04s
269:	learn: 0.5835143	total: 384ms	remaining: 1.04s
270:	learn: 0.5826402	total: 387ms	remaining: 1.04s
271:	learn: 0.5801974	total: 389ms	remaining: 1.04s
272:	learn: 0.5768706	total: 391ms	remaining: 1.04s
273:	learn: 0.5740141	total: 393ms	remaining: 1.04s
274:	learn: 0.5730162	total: 395ms	remaining: 1.04s
275:	learn: 0.5700836	total: 396ms	remaining: 1.04s
276:	learn: 0.5659051	total: 397ms	remaining: 1.04s
277:	learn: 0.5650227	total: 399ms	remaining: 1.04s
278:	learn: 0.5626060	total: 401ms	remaining: 1.03s
279:	learn: 0.5596339	total: 403ms	remaining: 1.04s
280:	learn: 0.5583378	total: 406ms	remaining: 1.04s
281:	learn: 0.5573131	total: 408ms	remaining: 1.04s
282:	learn: 0.5542297	total: 410ms	remaining: 1.04s
283:	learn: 0.5536617	total: 412ms	remaining: 1.04s
284:	learn: 0.5529102	total: 414ms	remaining: 1.04s
285:	learn: 0.5491585	total: 416ms	remaining: 1.04s
286:	learn: 0.5461252	total: 418ms	remaining: 1.04s
287:	learn: 0.5436402	total: 420ms	remaining: 1.04s
288:	learn: 0.5427511	total: 422ms	remaining: 1.04s
289:	learn: 0.5404556	total: 424ms	remaining: 1.04s
290:	learn: 0.5399054	total: 426ms	remaining: 1.04s
291:	learn: 0.5373049	total: 428ms	remaining: 1.04s
292:	learn: 0.5364279	total: 430ms	remaining: 1.04s
293:	learn: 0.5359949	total: 431ms	remaining: 1.04s
294:	learn: 0.5331994	total: 434ms	remaining: 1.04s
295:	learn: 0.5313836	total: 436ms	remaining: 1.03s
296:	learn: 0.5306450	total: 438ms	remaining: 1.03s
297:	learn: 0.5298532	total: 439ms	remaining: 1.03s
298:	learn: 0.5275951	total: 440ms	remaining: 1.03s
299:	learn: 0.5258703	total: 442ms	remaining: 1.03s
300:	learn: 0.5248464	total: 444ms	remaining: 1.03s
301:	learn: 0.5238978	total: 445ms	remaining: 1.03s
302:	learn: 0.5213813	total: 448ms	remaining: 1.03s
303:	learn: 0.5200807	total: 450ms	remaining: 1.03s
304:	learn: 0.5173564	total: 451ms	remaining: 1.03s
305:	learn: 0.5147158	total: 453ms	remaining: 1.03s
306:	learn: 0.5139970	total: 455ms	remaining: 1.03s
307:	learn: 0.5114543	total: 457ms	remaining: 1.03s
308:	learn: 0.5089955	total: 460ms	remaining: 1.03s
309:	learn: 0.5075921	total: 462ms	remaining: 1.03s
310:	learn: 0.5055878	total: 464ms	remaining: 1.03s
311:	learn: 0.5046780	total: 466ms	remaining: 1.03s
312:	learn: 0.5026173	total: 469ms	remaining: 1.03s
313:	learn: 0.5019369	total: 470ms	remaining: 1.03s
314:	learn: 0.5015884	total: 472ms	remaining: 1.02s
315:	learn: 0.5007262	total: 473ms	remaining: 1.02s
316:	learn: 0.4996129	total: 473ms	remaining: 1.02s
317:	learn: 0.4974297	total: 475ms	remaining: 1.02s
318:	learn: 0.4968258	total: 477ms	remaining: 1.02s
319:	learn: 0.4964952	total: 478ms	remaining: 1.01s
320:	learn: 0.4946516	total: 479ms	remaining: 1.01s
321:	learn: 0.4943120	total: 482ms	remaining: 1.01s
322:	learn: 0.4927456	total: 484ms	remaining: 1.01s
323:	learn: 0.4910107	total: 485ms	remaining: 1.01s
324:	learn: 0.4892001	total: 487ms	remaining: 1.01s
325:	learn: 0.4875366	total: 488ms	remaining: 1.01s
326:	learn: 0.4869838	total: 489ms	remaining: 1s
327:	learn: 0.4862486	total: 490ms	remaining: 1s
328:	learn: 0.4859032	total: 491ms	remaining: 1s
329:	learn: 0.4848002	total: 492ms	remaining: 998ms
330:	learn: 0.4832088	total: 493ms	remaining: 995ms
331:	learn: 0.4802705	total: 493ms	remaining: 993ms
332:	learn: 0.4782122	total: 494ms	remaining: 990ms
333:	learn: 0.4762408	total: 495ms	remaining: 988ms
334:	learn: 0.4742745	total: 496ms	remaining: 985ms
335:	learn: 0.4735871	total: 497ms	remaining: 983ms
336:	learn: 0.4733058	total: 498ms	remaining: 980ms
337:	learn: 0.4715863	total: 499ms	remaining: 978ms
338:	learn: 0.4700722	total: 500ms	remaining: 975ms
339:	learn: 0.4685302	total: 501ms	remaining: 973ms
340:	learn: 0.4671199	total: 502ms	remaining: 970ms

341:	learn: 0.4666582	total: 504ms	remaining: 970ms
342:	learn: 0.4650863	total: 505ms	remaining: 968ms
343:	learn: 0.4638166	total: 506ms	remaining: 965ms
344:	learn: 0.4612173	total: 507ms	remaining: 963ms
345:	learn: 0.4607783	total: 508ms	remaining: 960ms
346:	learn: 0.4593805	total: 509ms	remaining: 957ms
347:	learn: 0.4568300	total: 510ms	remaining: 955ms
348:	learn: 0.4564093	total: 510ms	remaining: 952ms
349:	learn: 0.4559969	total: 511ms	remaining: 950ms
350:	learn: 0.4552410	total: 512ms	remaining: 948ms
351:	learn: 0.4536801	total: 513ms	remaining: 945ms
352:	learn: 0.4521870	total: 514ms	remaining: 942ms
353:	learn: 0.4511775	total: 515ms	remaining: 940ms
354:	learn: 0.4497394	total: 516ms	remaining: 937ms
355:	learn: 0.4474225	total: 517ms	remaining: 935ms
356:	learn: 0.4462616	total: 518ms	remaining: 933ms
357:	learn: 0.4459117	total: 519ms	remaining: 931ms
358:	learn: 0.4451955	total: 520ms	remaining: 928ms
359:	learn: 0.4435767	total: 521ms	remaining: 926ms
360:	learn: 0.4422916	total: 522ms	remaining: 924ms
361:	learn: 0.4415779	total: 523ms	remaining: 921ms
362:	learn: 0.4400963	total: 524ms	remaining: 919ms
363:	learn: 0.4386974	total: 525ms	remaining: 917ms
364:	learn: 0.4375134	total: 530ms	remaining: 922ms
365:	learn: 0.4371694	total: 535ms	remaining: 927ms
366:	learn: 0.4361155	total: 536ms	remaining: 925ms
367:	learn: 0.4348882	total: 538ms	remaining: 924ms
368:	learn: 0.4334982	total: 539ms	remaining: 922ms
369:	learn: 0.4321776	total: 540ms	remaining: 920ms
370:	learn: 0.4310582	total: 541ms	remaining: 918ms
371:	learn: 0.4303235	total: 543ms	remaining: 916ms
372:	learn: 0.4301550	total: 544ms	remaining: 915ms
373:	learn: 0.4287421	total: 546ms	remaining: 913ms
374:	learn: 0.4282219	total: 546ms	remaining: 911ms
375:	learn: 0.4269721	total: 547ms	remaining: 908ms
376:	learn: 0.4257686	total: 548ms	remaining: 906ms
377:	learn: 0.4247161	total: 550ms	remaining: 905ms
378:	learn: 0.4245613	total: 551ms	remaining: 902ms
379:	learn: 0.4236943	total: 552ms	remaining: 900ms
380:	learn: 0.4226658	total: 553ms	remaining: 898ms
381:	learn: 0.4216985	total: 554ms	remaining: 897ms
382:	learn: 0.4213507	total: 555ms	remaining: 895ms
383:	learn: 0.4203222	total: 556ms	remaining: 892ms
384:	learn: 0.4201768	total: 557ms	remaining: 890ms
385:	learn: 0.4193356	total: 559ms	remaining: 889ms
386:	learn: 0.4182443	total: 560ms	remaining: 887ms
387:	learn: 0.4179063	total: 562ms	remaining: 886ms
388:	learn: 0.4159407	total: 563ms	remaining: 884ms
389:	learn: 0.4147630	total: 564ms	remaining: 883ms
390:	learn: 0.4144573	total: 565ms	remaining: 881ms
391:	learn: 0.4132776	total: 566ms	remaining: 878ms
392:	learn: 0.4123529	total: 568ms	remaining: 877ms
393:	learn: 0.4112107	total: 569ms	remaining: 875ms
394:	learn: 0.4101991	total: 571ms	remaining: 874ms
395:	learn: 0.4097070	total: 572ms	remaining: 873ms
396:	learn: 0.4086208	total: 573ms	remaining: 871ms
397:	learn: 0.4078163	total: 574ms	remaining: 869ms
398:	learn: 0.4069896	total: 576ms	remaining: 867ms
399:	learn: 0.4061203	total: 577ms	remaining: 866ms
400:	learn: 0.4051651	total: 579ms	remaining: 864ms
401:	learn: 0.4044408	total: 580ms	remaining: 862ms
402:	learn: 0.4040826	total: 581ms	remaining: 860ms
403:	learn: 0.4028872	total: 581ms	remaining: 858ms
404:	learn: 0.4026470	total: 583ms	remaining: 856ms
405:	learn: 0.4025462	total: 584ms	remaining: 855ms
406:	learn: 0.4017210	total: 586ms	remaining: 853ms
407:	learn: 0.3999588	total: 587ms	remaining: 852ms
408:	learn: 0.3990926	total: 588ms	remaining: 850ms
409:	learn: 0.3979813	total: 590ms	remaining: 849ms
410:	learn: 0.3969146	total: 591ms	remaining: 847ms
411:	learn: 0.3961071	total: 593ms	remaining: 846ms
412:	learn: 0.3951243	total: 594ms	remaining: 844ms
413:	learn: 0.3946928	total: 595ms	remaining: 842ms
414:	learn: 0.3943136	total: 596ms	remaining: 840ms
415:	learn: 0.3934199	total: 597ms	remaining: 838ms
416:	learn: 0.3926806	total: 599ms	remaining: 837ms
417:	learn: 0.3924876	total: 600ms	remaining: 835ms
418:	learn: 0.3924050	total: 601ms	remaining: 834ms
419:	learn: 0.3916445	total: 602ms	remaining: 832ms
420:	learn: 0.3908960	total: 604ms	remaining: 830ms
421:	learn: 0.3902419	total: 605ms	remaining: 829ms
422:	learn: 0.3899387	total: 606ms	remaining: 827ms
423:	learn: 0.3891015	total: 608ms	remaining: 825ms
424:	learn: 0.3881374	total: 609ms	remaining: 823ms
425:	learn: 0.3873755	total: 610ms	remaining: 821ms
426:	learn: 0.3867620	total: 610ms	remaining: 819ms
427:	learn: 0.3859772	total: 611ms	remaining: 817ms
428:	learn: 0.3851036	total: 613ms	remaining: 815ms
429:	learn: 0.3850289	total: 614ms	remaining: 814ms
430:	learn: 0.3842499	total: 615ms	remaining: 812ms
431:	learn: 0.3840395	total: 617ms	remaining: 811ms
432:	learn: 0.3833642	total: 618ms	remaining: 809ms
433:	learn: 0.3831191	total: 620ms	remaining: 808ms
434:	learn: 0.3825036	total: 621ms	remaining: 806ms
435:	learn: 0.3817166	total: 622ms	remaining: 805ms
436:	learn: 0.3808165	total: 623ms	remaining: 803ms
437:	learn: 0.3800330	total: 625ms	remaining: 802ms
438:	learn: 0.3793941	total: 626ms	remaining: 800ms
439:	learn: 0.3784259	total: 627ms	remaining: 798ms
440:	learn: 0.3778688	total: 628ms	remaining: 796ms
441:	learn: 0.3776897	total: 629ms	remaining: 794ms
442:	learn: 0.3769543	total: 631ms	remaining: 793ms
443:	learn: 0.3767229	total: 632ms	remaining: 791ms
444:	learn: 0.3761780	total: 633ms	remaining: 790ms
445:	learn: 0.3753296	total: 635ms	remaining: 788ms
446:	learn: 0.3741322	total: 636ms	remaining: 787ms
447:	learn: 0.3733077	total: 637ms	remaining: 785ms
448:	learn: 0.3721461	total: 639ms	remaining: 784ms
449:	learn: 0.3713840	total: 640ms	remaining: 782ms
450:	learn: 0.3706879	total: 641ms	remaining: 780ms
451:	learn: 0.3700186	total: 642ms	remaining: 778ms
452:	learn: 0.3698085	total: 643ms	remaining: 777ms
453:	learn: 0.3690742	total: 645ms	remaining: 775ms
454:	learn: 0.3685887	total: 646ms	remaining: 774ms
455:	learn: 0.3683747	total: 647ms	remaining: 772ms
456:	learn: 0.3676091	total: 648ms	remaining: 770ms
457:	learn: 0.3665134	total: 650ms	remaining: 769ms
458:	learn: 0.3659285	total: 651ms	remaining: 767ms
459:	learn: 0.3656782	total: 652ms	remaining: 766ms
460:	learn: 0.3649836	total: 654ms	remaining: 764ms
461:	learn: 0.3647464	total: 655ms	remaining: 762ms
462:	learn: 0.3645100	total: 656ms	remaining: 760ms
463:	learn: 0.3639368	total: 657ms	remaining: 759ms
464:	learn: 0.3628901	total: 658ms	remaining: 757ms
465:	learn: 0.3618851	total: 659ms	remaining: 756ms
466:	learn: 0.3611446	total: 661ms	remaining: 754ms
467:	learn: 0.3605215	total: 662ms	remaining: 753ms
468:	learn: 0.3597779	total: 663ms	remaining: 751ms
469:	learn: 0.3591858	total: 665ms	remaining: 750ms
470:	learn: 0.3582276	total: 666ms	remaining: 748ms
471:	learn: 0.3572608	total: 667ms	remaining: 746ms
472:	learn: 0.3563831	total: 669ms	remaining: 745ms
473:	learn: 0.3561628	total: 670ms	remaining: 743ms
474:	learn: 0.3556690	total: 670ms	remaining: 741ms
475:	learn: 0.3550552	total: 671ms	remaining: 739ms
476:	learn: 0.3544715	total: 672ms	remaining: 737ms
477:	learn: 0.3534138	total: 674ms	remaining: 736ms
478:	learn: 0.3524651	total: 675ms	remaining: 734ms
479:	learn: 0.3520129	total: 676ms	remaining: 732ms
480:	learn: 0.3513117	total: 677ms	remaining: 731ms
481:	learn: 0.3504924	total: 679ms	remaining: 729ms
482:	learn: 0.3498295	total: 680ms	remaining: 728ms
483:	learn: 0.3486562	total: 681ms	remaining: 726ms
484:	learn: 0.3481617	total: 682ms	remaining: 725ms
485:	learn: 0.3472853	total: 684ms	remaining: 723ms
486:	learn: 0.3466406	total: 685ms	remaining: 722ms
487:	learn: 0.3462553	total: 686ms	remaining: 720ms
488:	learn: 0.3460178	total: 688ms	remaining: 719ms
489:	learn: 0.3449908	total: 689ms	remaining: 717ms
490:	learn: 0.3441306	total: 691ms	remaining: 716ms
491:	learn: 0.3439705	total: 693ms	remaining: 715ms
492:	learn: 0.3434042	total: 694ms	remaining: 714ms
493:	learn: 0.3425150	total: 696ms	remaining: 713ms
494:	learn: 0.3417017	total: 697ms	remaining: 712ms
495:	learn: 0.3412884	total: 700ms	remaining: 711ms
496:	learn: 0.3407886	total: 701ms	remaining: 709ms
497:	learn: 0.3396737	total: 702ms	remaining: 708ms
498:	learn: 0.3391164	total: 704ms	remaining: 706ms
499:	learn: 0.3388526	total: 705ms	remaining: 705ms
500:	learn: 0.3381614	total: 706ms	remaining: 704ms
501:	learn: 0.3377742	total: 708ms	remaining: 702ms
502:	learn: 0.3372747	total: 709ms	remaining: 701ms
503:	learn: 0.3365582	total: 711ms	remaining: 700ms
504:	learn: 0.3355089	total: 712ms	remaining: 698ms
505:	learn: 0.3346844	total: 714ms	remaining: 697ms
506:	learn: 0.3338520	total: 715ms	remaining: 696ms
507:	learn: 0.3334925	total: 716ms	remaining: 694ms
508:	learn: 0.3326657	total: 717ms	remaining: 692ms
509:	learn: 0.3318727	total: 718ms	remaining: 690ms
510:	learn: 0.3317197	total: 720ms	remaining: 689ms
511:	learn: 0.3310815	total: 721ms	remaining: 687ms
512:	learn: 0.3299818	total: 722ms	remaining: 685ms
513:	learn: 0.3294332	total: 723ms	remaining: 684ms
514:	learn: 0.3287882	total: 725ms	remaining: 683ms
515:	learn: 0.3283417	total: 726ms	remaining: 681ms
516:	learn: 0.3280769	total: 728ms	remaining: 680ms
517:	learn: 0.3279321	total: 729ms	remaining: 678ms
518:	learn: 0.3272399	total: 730ms	remaining: 677ms
519:	learn: 0.3266112	total: 731ms	remaining: 675ms
520:	learn: 0.3260841	total: 732ms	remaining: 673ms
521:	learn: 0.3253560	total: 734ms	remaining: 672ms
522:	learn: 0.3244617	total: 735ms	remaining: 670ms
523:	learn: 0.3234024	total: 736ms	remaining: 669ms
524:	learn: 0.3229272	total: 738ms	remaining: 668ms
525:	learn: 0.3224111	total: 739ms	remaining: 666ms
526:	learn: 0.3218218	total: 741ms	remaining: 665ms
527:	learn: 0.3212833	total: 742ms	remaining: 663ms
528:	learn: 0.3205502	total: 744ms	remaining: 662ms
529:	learn: 0.3201341	total: 745ms	remaining: 661ms
530:	learn: 0.3196921	total: 746ms	remaining: 659ms
531:	learn: 0.3192777	total: 747ms	remaining: 657ms
532:	learn: 0.3189474	total: 748ms	remaining: 655ms
533:	learn: 0.3183194	total: 749ms	remaining: 653ms
534:	learn: 0.3178075	total: 750ms	remaining: 652ms
535:	learn: 0.3172569	total: 751ms	remaining: 651ms
536:	learn: 0.3168053	total: 753ms	remaining: 649ms
537:	learn: 0.3156811	total: 754ms	remaining: 648ms
538:	learn: 0.3143918	total: 756ms	remaining: 646ms
539:	learn: 0.3143647	total: 757ms	remaining: 645ms
540:	learn: 0.3139978	total: 758ms	remaining: 643ms
541:	learn: 0.3131241	total: 760ms	remaining: 642ms
542:	learn: 0.3126738	total: 761ms	remaining: 640ms
543:	learn: 0.3118581	total: 762ms	remaining: 639ms
544:	learn: 0.3109724	total: 763ms	remaining: 637ms
545:	learn: 0.3103741	total: 765ms	remaining: 636ms
546:	learn: 0.3096018	total: 766ms	remaining: 635ms
547:	learn: 0.3087659	total: 768ms	remaining: 634ms
548:	learn: 0.3077102	total: 770ms	remaining: 632ms
549:	learn: 0.3069105	total: 772ms	remaining: 631ms
550:	learn: 0.3065646	total: 773ms	remaining: 630ms
551:	learn: 0.3054940	total: 775ms	remaining: 629ms
552:	learn: 0.3050904	total: 776ms	remaining: 627ms
553:	learn: 0.3045977	total: 778ms	remaining: 626ms
554:	learn: 0.3038565	total: 779ms	remaining: 625ms
555:	learn: 0.3034369	total: 781ms	remaining: 623ms
556:	learn: 0.3026029	total: 782ms	remaining: 622ms
557:	learn: 0.3024937	total: 784ms	remaining: 621ms
558:	learn: 0.3024700	total: 785ms	remaining: 619ms
559:	learn: 0.3020178	total: 786ms	remaining: 618ms
560:	learn: 0.3014979	total: 788ms	remaining: 617ms
561:	learn: 0.3011579	total: 789ms	remaining: 615ms
562:	learn: 0.3009640	total: 790ms	remaining: 613ms
563:	learn: 0.3003658	total: 792ms	remaining: 612ms
564:	learn: 0.2996863	total: 793ms	remaining: 611ms
565:	learn: 0.2996592	total: 795ms	remaining: 609ms
566:	learn: 0.2992890	total: 796ms	remaining: 608ms
567:	learn: 0.2986695	total: 798ms	remaining: 607ms
568:	learn: 0.2984452	total: 799ms	remaining: 605ms
569:	learn: 0.2978889	total: 800ms	remaining: 604ms
570:	learn: 0.2972432	total: 802ms	remaining: 602ms
571:	learn: 0.2972218	total: 803ms	remaining: 601ms
572:	learn: 0.2964255	total: 804ms	remaining: 599ms
573:	learn: 0.2959421	total: 806ms	remaining: 598ms
574:	learn: 0.2953803	total: 807ms	remaining: 597ms
575:	learn: 0.2950309	total: 808ms	remaining: 595ms
576:	learn: 0.2942184	total: 810ms	remaining: 594ms
577:	learn: 0.2937902	total: 812ms	remaining: 593ms
578:	learn: 0.2934079	total: 813ms	remaining: 591ms
579:	learn: 0.2932856	total: 815ms	remaining: 590ms
580:	learn: 0.2923071	total: 817ms	remaining: 589ms
581:	learn: 0.2920590	total: 818ms	remaining: 588ms
582:	learn: 0.2917231	total: 819ms	remaining: 586ms
583:	learn: 0.2913759	total: 820ms	remaining: 584ms
584:	learn: 0.2910147	total: 822ms	remaining: 583ms
585:	learn: 0.2907131	total: 823ms	remaining: 581ms
586:	learn: 0.2901588	total: 824ms	remaining: 580ms
587:	learn: 0.2900236	total: 826ms	remaining: 579ms
588:	learn: 0.2895594	total: 827ms	remaining: 577ms
589:	learn: 0.2894602	total: 829ms	remaining: 576ms
590:	learn: 0.2887509	total: 830ms	remaining: 575ms
591:	learn: 0.2881116	total: 832ms	remaining: 573ms
592:	learn: 0.2874994	total: 834ms	remaining: 572ms
593:	learn: 0.2867798	total: 835ms	remaining: 571ms
594:	learn: 0.2867614	total: 837ms	remaining: 569ms
595:	learn: 0.2864149	total: 837ms	remaining: 568ms
596:	learn: 0.2856932	total: 839ms	remaining: 567ms
597:	learn: 0.2849095	total: 841ms	remaining: 565ms
598:	learn: 0.2845421	total: 843ms	remaining: 564ms
599:	learn: 0.2841414	total: 845ms	remaining: 563ms
600:	learn: 0.2834480	total: 846ms	remaining: 562ms
601:	learn: 0.2829908	total: 848ms	remaining: 561ms
602:	learn: 0.2822115	total: 850ms	remaining: 559ms
603:	learn: 0.2816319	total: 851ms	remaining: 558ms
604:	learn: 0.2811305	total: 853ms	remaining: 557ms
605:	learn: 0.2809157	total: 855ms	remaining: 556ms
606:	learn: 0.2808982	total: 858ms	remaining: 555ms
607:	learn: 0.2804830	total: 860ms	remaining: 555ms
608:	learn: 0.2803643	total: 863ms	remaining: 554ms
609:	learn: 0.2797839	total: 865ms	remaining: 553ms
610:	learn: 0.2788472	total: 866ms	remaining: 551ms
611:	learn: 0.2786047	total: 868ms	remaining: 550ms
612:	learn: 0.2782883	total: 871ms	remaining: 550ms
613:	learn: 0.2777063	total: 873ms	remaining: 549ms
614:	learn: 0.2773401	total: 874ms	remaining: 547ms
615:	learn: 0.2761539	total: 875ms	remaining: 546ms
616:	learn: 0.2747891	total: 877ms	remaining: 544ms
617:	learn: 0.2743856	total: 879ms	remaining: 543ms
618:	learn: 0.2740925	total: 880ms	remaining: 542ms
619:	learn: 0.2727901	total: 882ms	remaining: 541ms
620:	learn: 0.2722364	total: 884ms	remaining: 539ms
621:	learn: 0.2722213	total: 885ms	remaining: 538ms
622:	learn: 0.2720994	total: 886ms	remaining: 536ms
623:	learn: 0.2714656	total: 888ms	remaining: 535ms
624:	learn: 0.2709076	total: 889ms	remaining: 534ms
625:	learn: 0.2707940	total: 891ms	remaining: 532ms
626:	learn: 0.2705056	total: 893ms	remaining: 531ms
627:	learn: 0.2701863	total: 895ms	remaining: 530ms
628:	learn: 0.2699908	total: 896ms	remaining: 529ms

629:	learn: 0.2698772	total: 899ms	remaining: 528ms
630:	learn: 0.2694900	total: 901ms	remaining: 527ms
631:	learn: 0.2694655	total: 902ms	remaining: 525ms
632:	learn: 0.2693125	total: 903ms	remaining: 524ms
633:	learn: 0.2692378	total: 905ms	remaining: 523ms
634:	learn: 0.2687140	total: 908ms	remaining: 522ms
635:	learn: 0.2679325	total: 910ms	remaining: 521ms
636:	learn: 0.2676401	total: 911ms	remaining: 519ms
637:	learn: 0.2669670	total: 913ms	remaining: 518ms
638:	learn: 0.2665587	total: 914ms	remaining: 516ms
639:	learn: 0.2660998	total: 915ms	remaining: 515ms
640:	learn: 0.2656080	total: 917ms	remaining: 514ms
641:	learn: 0.2652602	total: 919ms	remaining: 512ms
642:	learn: 0.2649154	total: 920ms	remaining: 511ms
643:	learn: 0.2647335	total: 921ms	remaining: 509ms
644:	learn: 0.2643590	total: 922ms	remaining: 508ms
645:	learn: 0.2642074	total: 923ms	remaining: 506ms
646:	learn: 0.2636413	total: 924ms	remaining: 504ms
647:	learn: 0.2634547	total: 925ms	remaining: 503ms
648:	learn: 0.2633234	total: 927ms	remaining: 502ms
649:	learn: 0.2631459	total: 929ms	remaining: 500ms
650:	learn: 0.2628776	total: 931ms	remaining: 499ms
651:	learn: 0.2627040	total: 932ms	remaining: 498ms
652:	learn: 0.2623288	total: 935ms	remaining: 497ms
653:	learn: 0.2618748	total: 937ms	remaining: 495ms
654:	learn: 0.2614101	total: 938ms	remaining: 494ms
655:	learn: 0.2612233	total: 940ms	remaining: 493ms
656:	learn: 0.2607019	total: 942ms	remaining: 492ms
657:	learn: 0.2601612	total: 943ms	remaining: 490ms
658:	learn: 0.2591871	total: 944ms	remaining: 488ms
659:	learn: 0.2588474	total: 945ms	remaining: 487ms
660:	learn: 0.2586845	total: 947ms	remaining: 486ms
661:	learn: 0.2583239	total: 949ms	remaining: 484ms
662:	learn: 0.2580298	total: 951ms	remaining: 483ms
663:	learn: 0.2575000	total: 953ms	remaining: 482ms
664:	learn: 0.2565597	total: 954ms	remaining: 481ms
665:	learn: 0.2563298	total: 956ms	remaining: 480ms
666:	learn: 0.2556599	total: 958ms	remaining: 478ms
667:	learn: 0.2554127	total: 959ms	remaining: 477ms
668:	learn: 0.2549176	total: 961ms	remaining: 476ms
669:	learn: 0.2545791	total: 963ms	remaining: 474ms
670:	learn: 0.2544533	total: 965ms	remaining: 473ms
671:	learn: 0.2540192	total: 967ms	remaining: 472ms
672:	learn: 0.2536250	total: 969ms	remaining: 471ms
673:	learn: 0.2531327	total: 971ms	remaining: 470ms
674:	learn: 0.2527369	total: 973ms	remaining: 469ms
675:	learn: 0.2523342	total: 974ms	remaining: 467ms
676:	learn: 0.2521870	total: 976ms	remaining: 465ms
677:	learn: 0.2519848	total: 977ms	remaining: 464ms
678:	learn: 0.2518208	total: 979ms	remaining: 463ms
679:	learn: 0.2514272	total: 981ms	remaining: 462ms
680:	learn: 0.2506439	total: 983ms	remaining: 460ms
681:	learn: 0.2505056	total: 985ms	remaining: 459ms
682:	learn: 0.2500129	total: 987ms	remaining: 458ms
683:	learn: 0.2498438	total: 989ms	remaining: 457ms
684:	learn: 0.2496704	total: 990ms	remaining: 455ms
685:	learn: 0.2491925	total: 991ms	remaining: 454ms
686:	learn: 0.2488220	total: 993ms	remaining: 452ms
687:	learn: 0.2486639	total: 995ms	remaining: 451ms
688:	learn: 0.2478116	total: 997ms	remaining: 450ms
689:	learn: 0.2476588	total: 999ms	remaining: 449ms
690:	learn: 0.2472574	total: 1s	remaining: 448ms
691:	learn: 0.2465678	total: 1s	remaining: 447ms
692:	learn: 0.2463907	total: 1s	remaining: 445ms
693:	learn: 0.2458022	total: 1.01s	remaining: 444ms
694:	learn: 0.2455386	total: 1.01s	remaining: 443ms
695:	learn: 0.2454321	total: 1.01s	remaining: 441ms
696:	learn: 0.2453940	total: 1.01s	remaining: 440ms
697:	learn: 0.2450189	total: 1.01s	remaining: 439ms
698:	learn: 0.2447416	total: 1.02s	remaining: 438ms
699:	learn: 0.2445892	total: 1.02s	remaining: 436ms
700:	learn: 0.2445293	total: 1.02s	remaining: 435ms
701:	learn: 0.2444009	total: 1.02s	remaining: 433ms
702:	learn: 0.2435871	total: 1.02s	remaining: 431ms
703:	learn: 0.2432681	total: 1.02s	remaining: 430ms
704:	learn: 0.2431668	total: 1.02s	remaining: 429ms
705:	learn: 0.2428405	total: 1.03s	remaining: 428ms
706:	learn: 0.2425017	total: 1.03s	remaining: 427ms
707:	learn: 0.2421681	total: 1.03s	remaining: 426ms
708:	learn: 0.2418227	total: 1.03s	remaining: 424ms
709:	learn: 0.2415892	total: 1.03s	remaining: 422ms
710:	learn: 0.2411769	total: 1.04s	remaining: 421ms
711:	learn: 0.2407398	total: 1.04s	remaining: 420ms
712:	learn: 0.2404397	total: 1.04s	remaining: 419ms
713:	learn: 0.2401122	total: 1.04s	remaining: 418ms
714:	learn: 0.2399197	total: 1.04s	remaining: 416ms
715:	learn: 0.2393801	total: 1.05s	remaining: 415ms
716:	learn: 0.2392390	total: 1.05s	remaining: 414ms
717:	learn: 0.2389319	total: 1.05s	remaining: 412ms
718:	learn: 0.2385929	total: 1.05s	remaining: 410ms
719:	learn: 0.2379564	total: 1.05s	remaining: 409ms
720:	learn: 0.2373628	total: 1.05s	remaining: 407ms
721:	learn: 0.2365997	total: 1.05s	remaining: 406ms
722:	learn: 0.2362939	total: 1.05s	remaining: 405ms
723:	learn: 0.2361603	total: 1.06s	remaining: 403ms
724:	learn: 0.2359816	total: 1.06s	remaining: 402ms
725:	learn: 0.2359193	total: 1.06s	remaining: 401ms
726:	learn: 0.2357814	total: 1.06s	remaining: 399ms
727:	learn: 0.2356375	total: 1.06s	remaining: 398ms
728:	learn: 0.2354533	total: 1.07s	remaining: 397ms
729:	learn: 0.2349650	total: 1.07s	remaining: 395ms
730:	learn: 0.2346473	total: 1.07s	remaining: 393ms
731:	learn: 0.2342174	total: 1.07s	remaining: 392ms
732:	learn: 0.2340946	total: 1.07s	remaining: 391ms
733:	learn: 0.2339245	total: 1.07s	remaining: 389ms
734:	learn: 0.2337795	total: 1.07s	remaining: 388ms
735:	learn: 0.2330252	total: 1.08s	remaining: 386ms
736:	learn: 0.2326213	total: 1.08s	remaining: 385ms
737:	learn: 0.2323013	total: 1.08s	remaining: 384ms
738:	learn: 0.2321572	total: 1.08s	remaining: 383ms
739:	learn: 0.2318163	total: 1.08s	remaining: 381ms
740:	learn: 0.2315278	total: 1.09s	remaining: 380ms
741:	learn: 0.2313978	total: 1.09s	remaining: 379ms
742:	learn: 0.2310017	total: 1.09s	remaining: 377ms
743:	learn: 0.2309821	total: 1.09s	remaining: 376ms
744:	learn: 0.2306698	total: 1.09s	remaining: 374ms
745:	learn: 0.2303923	total: 1.09s	remaining: 373ms
746:	learn: 0.2302342	total: 1.1s	remaining: 371ms
747:	learn: 0.2299127	total: 1.1s	remaining: 370ms
748:	learn: 0.2296291	total: 1.1s	remaining: 368ms
749:	learn: 0.2293282	total: 1.1s	remaining: 367ms
750:	learn: 0.2291871	total: 1.1s	remaining: 365ms
751:	learn: 0.2290123	total: 1.1s	remaining: 364ms
752:	learn: 0.2287259	total: 1.1s	remaining: 362ms
753:	learn: 0.2286103	total: 1.1s	remaining: 360ms
754:	learn: 0.2281509	total: 1.11s	remaining: 359ms
755:	learn: 0.2280779	total: 1.11s	remaining: 358ms
756:	learn: 0.2278034	total: 1.11s	remaining: 356ms
757:	learn: 0.2275138	total: 1.11s	remaining: 355ms
758:	learn: 0.2274252	total: 1.11s	remaining: 353ms
759:	learn: 0.2268992	total: 1.11s	remaining: 352ms
760:	learn: 0.2262463	total: 1.11s	remaining: 350ms
761:	learn: 0.2258611	total: 1.12s	remaining: 349ms
762:	learn: 0.2256410	total: 1.12s	remaining: 348ms
763:	learn: 0.2253817	total: 1.12s	remaining: 346ms
764:	learn: 0.2251249	total: 1.12s	remaining: 345ms
765:	learn: 0.2250013	total: 1.12s	remaining: 344ms
766:	learn: 0.2245309	total: 1.13s	remaining: 342ms
767:	learn: 0.2243799	total: 1.13s	remaining: 341ms
768:	learn: 0.2240462	total: 1.13s	remaining: 339ms
769:	learn: 0.2239907	total: 1.13s	remaining: 337ms
770:	learn: 0.2238341	total: 1.13s	remaining: 336ms
771:	learn: 0.2234166	total: 1.13s	remaining: 334ms
772:	learn: 0.2230438	total: 1.13s	remaining: 333ms
773:	learn: 0.2227529	total: 1.13s	remaining: 331ms
774:	learn: 0.2226682	total: 1.14s	remaining: 330ms
775:	learn: 0.2223479	total: 1.14s	remaining: 329ms
776:	learn: 0.2222323	total: 1.14s	remaining: 327ms
777:	learn: 0.2221280	total: 1.14s	remaining: 326ms
778:	learn: 0.2220763	total: 1.14s	remaining: 324ms
779:	learn: 0.2216915	total: 1.14s	remaining: 322ms
780:	learn: 0.2216419	total: 1.14s	remaining: 321ms
781:	learn: 0.2215312	total: 1.15s	remaining: 320ms
782:	learn: 0.2211392	total: 1.15s	remaining: 318ms
783:	learn: 0.2208211	total: 1.15s	remaining: 317ms
784:	learn: 0.2203257	total: 1.15s	remaining: 316ms
785:	learn: 0.2202729	total: 1.15s	remaining: 314ms
786:	learn: 0.2202628	total: 1.16s	remaining: 313ms
787:	learn: 0.2201430	total: 1.16s	remaining: 311ms
788:	learn: 0.2199042	total: 1.16s	remaining: 310ms
789:	learn: 0.2197572	total: 1.16s	remaining: 308ms
790:	learn: 0.2195102	total: 1.16s	remaining: 307ms
791:	learn: 0.2191971	total: 1.16s	remaining: 306ms
792:	learn: 0.2188043	total: 1.17s	remaining: 304ms
793:	learn: 0.2186894	total: 1.17s	remaining: 303ms
794:	learn: 0.2184519	total: 1.17s	remaining: 302ms
795:	learn: 0.2181500	total: 1.17s	remaining: 300ms
796:	learn: 0.2179103	total: 1.17s	remaining: 299ms
797:	learn: 0.2176855	total: 1.17s	remaining: 297ms
798:	learn: 0.2176518	total: 1.18s	remaining: 296ms
799:	learn: 0.2173697	total: 1.18s	remaining: 294ms
800:	learn: 0.2172626	total: 1.18s	remaining: 293ms
801:	learn: 0.2170220	total: 1.18s	remaining: 291ms
802:	learn: 0.2166002	total: 1.18s	remaining: 290ms
803:	learn: 0.2165547	total: 1.18s	remaining: 289ms
804:	learn: 0.2164329	total: 1.19s	remaining: 287ms
805:	learn: 0.2162753	total: 1.19s	remaining: 286ms
806:	learn: 0.2159012	total: 1.19s	remaining: 285ms
807:	learn: 0.2154819	total: 1.19s	remaining: 283ms
808:	learn: 0.2151236	total: 1.19s	remaining: 282ms
809:	learn: 0.2150232	total: 1.2s	remaining: 281ms
810:	learn: 0.2147269	total: 1.2s	remaining: 279ms
811:	learn: 0.2144379	total: 1.2s	remaining: 278ms
812:	learn: 0.2141411	total: 1.2s	remaining: 277ms
813:	learn: 0.2139953	total: 1.2s	remaining: 275ms
814:	learn: 0.2133862	total: 1.21s	remaining: 274ms
815:	learn: 0.2130338	total: 1.21s	remaining: 272ms
816:	learn: 0.2129237	total: 1.21s	remaining: 271ms
817:	learn: 0.2127782	total: 1.21s	remaining: 270ms
818:	learn: 0.2124275	total: 1.21s	remaining: 268ms
819:	learn: 0.2121484	total: 1.21s	remaining: 267ms
820:	learn: 0.2120802	total: 1.22s	remaining: 265ms
821:	learn: 0.2118706	total: 1.22s	remaining: 264ms
822:	learn: 0.2116208	total: 1.22s	remaining: 262ms
823:	learn: 0.2115066	total: 1.22s	remaining: 261ms
824:	learn: 0.2111249	total: 1.22s	remaining: 259ms
825:	learn: 0.2109701	total: 1.22s	remaining: 258ms
826:	learn: 0.2109592	total: 1.23s	remaining: 256ms
827:	learn: 0.2108256	total: 1.23s	remaining: 255ms
828:	learn: 0.2102545	total: 1.23s	remaining: 253ms
829:	learn: 0.2101135	total: 1.23s	remaining: 252ms
830:	learn: 0.2097579	total: 1.23s	remaining: 251ms
831:	learn: 0.2095842	total: 1.23s	remaining: 249ms
832:	learn: 0.2093203	total: 1.23s	remaining: 248ms
833:	learn: 0.2090260	total: 1.24s	remaining: 246ms
834:	learn: 0.2087808	total: 1.24s	remaining: 244ms
835:	learn: 0.2083321	total: 1.24s	remaining: 243ms
836:	learn: 0.2082910	total: 1.24s	remaining: 241ms
837:	learn: 0.2079548	total: 1.24s	remaining: 240ms
838:	learn: 0.2078442	total: 1.24s	remaining: 238ms
839:	learn: 0.2074924	total: 1.24s	remaining: 237ms
840:	learn: 0.2070626	total: 1.24s	remaining: 235ms
841:	learn: 0.2068076	total: 1.24s	remaining: 233ms
842:	learn: 0.2065549	total: 1.24s	remaining: 232ms
843:	learn: 0.2060633	total: 1.25s	remaining: 230ms
844:	learn: 0.2059610	total: 1.25s	remaining: 229ms
845:	learn: 0.2056987	total: 1.25s	remaining: 227ms
846:	learn: 0.2053958	total: 1.25s	remaining: 226ms
847:	learn: 0.2052236	total: 1.25s	remaining: 224ms
848:	learn: 0.2048739	total: 1.25s	remaining: 223ms
849:	learn: 0.2046081	total: 1.25s	remaining: 221ms
850:	learn: 0.2044984	total: 1.25s	remaining: 220ms
851:	learn: 0.2041813	total: 1.25s	remaining: 218ms
852:	learn: 0.2039566	total: 1.26s	remaining: 217ms
853:	learn: 0.2036917	total: 1.26s	remaining: 215ms
854:	learn: 0.2034463	total: 1.26s	remaining: 213ms
855:	learn: 0.2031633	total: 1.26s	remaining: 212ms
856:	learn: 0.2029292	total: 1.26s	remaining: 210ms
857:	learn: 0.2022780	total: 1.26s	remaining: 209ms
858:	learn: 0.2019247	total: 1.26s	remaining: 207ms
859:	learn: 0.2018195	total: 1.26s	remaining: 206ms
860:	learn: 0.2015247	total: 1.27s	remaining: 204ms
861:	learn: 0.2014005	total: 1.27s	remaining: 203ms
862:	learn: 0.2011773	total: 1.27s	remaining: 201ms
863:	learn: 0.2008768	total: 1.27s	remaining: 200ms
864:	learn: 0.2006035	total: 1.27s	remaining: 198ms
865:	learn: 0.2003521	total: 1.27s	remaining: 197ms
866:	learn: 0.2000703	total: 1.27s	remaining: 195ms
867:	learn: 0.1997815	total: 1.27s	remaining: 194ms
868:	learn: 0.1996701	total: 1.28s	remaining: 192ms
869:	learn: 0.1995013	total: 1.28s	remaining: 191ms

870:	learn: 0.1993631	total: 1.28s	remaining: 189ms
871:	learn: 0.1990543	total: 1.28s	remaining: 188ms
872:	learn: 0.1987681	total: 1.28s	remaining: 186ms
873:	learn: 0.1985726	total: 1.28s	remaining: 185ms
874:	learn: 0.1985164	total: 1.28s	remaining: 183ms
875:	learn: 0.1982975	total: 1.28s	remaining: 182ms
876:	learn: 0.1979208	total: 1.28s	remaining: 180ms
877:	learn: 0.1976325	total: 1.29s	remaining: 179ms
878:	learn: 0.1973071	total: 1.29s	remaining: 177ms
879:	learn: 0.1970358	total: 1.29s	remaining: 176ms
880:	learn: 0.1968793	total: 1.29s	remaining: 174ms
881:	learn: 0.1967096	total: 1.29s	remaining: 173ms
882:	learn: 0.1964732	total: 1.29s	remaining: 171ms
883:	learn: 0.1963016	total: 1.29s	remaining: 170ms
884:	learn: 0.1959125	total: 1.29s	remaining: 168ms
885:	learn: 0.1957200	total: 1.29s	remaining: 167ms
886:	learn: 0.1953929	total: 1.3s	remaining: 165ms
887:	learn: 0.1951273	total: 1.3s	remaining: 164ms
888:	learn: 0.1947683	total: 1.3s	remaining: 162ms
889:	learn: 0.1946642	total: 1.3s	remaining: 161ms
890:	learn: 0.1943321	total: 1.3s	remaining: 159ms
891:	learn: 0.1940924	total: 1.3s	remaining: 158ms
892:	learn: 0.1938925	total: 1.3s	remaining: 156ms
893:	learn: 0.1938821	total: 1.3s	remaining: 155ms
894:	learn: 0.1937845	total: 1.31s	remaining: 153ms
895:	learn: 0.1937543	total: 1.31s	remaining: 152ms
896:	learn: 0.1935213	total: 1.31s	remaining: 150ms
897:	learn: 0.1934098	total: 1.31s	remaining: 149ms
898:	learn: 0.1931640	total: 1.31s	remaining: 147ms
899:	learn: 0.1929307	total: 1.31s	remaining: 146ms
900:	learn: 0.1926570	total: 1.31s	remaining: 144ms
901:	learn: 0.1923192	total: 1.31s	remaining: 143ms
902:	learn: 0.1920204	total: 1.31s	remaining: 141ms
903:	learn: 0.1918312	total: 1.32s	remaining: 140ms
904:	learn: 0.1917920	total: 1.32s	remaining: 138ms
905:	learn: 0.1915238	total: 1.32s	remaining: 137ms
906:	learn: 0.1914084	total: 1.32s	remaining: 135ms
907:	learn: 0.1913478	total: 1.32s	remaining: 134ms
908:	learn: 0.1910808	total: 1.32s	remaining: 132ms
909:	learn: 0.1908408	total: 1.32s	remaining: 131ms
910:	learn: 0.1906459	total: 1.32s	remaining: 129ms
911:	learn: 0.1903726	total: 1.32s	remaining: 128ms
912:	learn: 0.1901369	total: 1.33s	remaining: 126ms
913:	learn: 0.1898608	total: 1.33s	remaining: 125ms
914:	learn: 0.1898072	total: 1.33s	remaining: 123ms
915:	learn: 0.1894046	total: 1.33s	remaining: 122ms
916:	learn: 0.1893929	total: 1.33s	remaining: 120ms
917:	learn: 0.1892177	total: 1.33s	remaining: 119ms
918:	learn: 0.1890792	total: 1.33s	remaining: 117ms
919:	learn: 0.1888648	total: 1.33s	remaining: 116ms
920:	learn: 0.1886742	total: 1.33s	remaining: 115ms
921:	learn: 0.1885450	total: 1.34s	remaining: 113ms
922:	learn: 0.1880416	total: 1.34s	remaining: 112ms
923:	learn: 0.1878829	total: 1.34s	remaining: 110ms
924:	learn: 0.1877425	total: 1.34s	remaining: 109ms
925:	learn: 0.1875365	total: 1.34s	remaining: 107ms
926:	learn: 0.1873585	total: 1.34s	remaining: 106ms
927:	learn: 0.1873292	total: 1.34s	remaining: 104ms
928:	learn: 0.1868225	total: 1.34s	remaining: 103ms
929:	learn: 0.1867526	total: 1.34s	remaining: 101ms
930:	learn: 0.1867072	total: 1.35s	remaining: 99.8ms
931:	learn: 0.1862086	total: 1.35s	remaining: 98.4ms
932:	learn: 0.1860615	total: 1.35s	remaining: 96.9ms
933:	learn: 0.1857820	total: 1.35s	remaining: 95.5ms
934:	learn: 0.1855730	total: 1.35s	remaining: 94ms
935:	learn: 0.1853176	total: 1.35s	remaining: 92.6ms
936:	learn: 0.1851143	total: 1.35s	remaining: 91.1ms
937:	learn: 0.1848972	total: 1.35s	remaining: 89.6ms
938:	learn: 0.1845620	total: 1.36s	remaining: 88.2ms
939:	learn: 0.1843965	total: 1.36s	remaining: 86.7ms
940:	learn: 0.1837907	total: 1.36s	remaining: 85.2ms
941:	learn: 0.1833425	total: 1.36s	remaining: 83.8ms
942:	learn: 0.1832254	total: 1.36s	remaining: 82.3ms
943:	learn: 0.1829773	total: 1.36s	remaining: 80.9ms
944:	learn: 0.1827720	total: 1.36s	remaining: 79.4ms
945:	learn: 0.1825633	total: 1.36s	remaining: 78ms
946:	learn: 0.1823471	total: 1.37s	remaining: 76.5ms
947:	learn: 0.1820763	total: 1.37s	remaining: 75.1ms
948:	learn: 0.1817146	total: 1.37s	remaining: 73.6ms
949:	learn: 0.1814335	total: 1.37s	remaining: 72.1ms
950:	learn: 0.1813405	total: 1.37s	remaining: 70.7ms
951:	learn: 0.1811681	total: 1.37s	remaining: 69.2ms
952:	learn: 0.1809714	total: 1.37s	remaining: 67.8ms
953:	learn: 0.1808260	total: 1.38s	remaining: 66.3ms
954:	learn: 0.1808011	total: 1.38s	remaining: 64.9ms
955:	learn: 0.1805731	total: 1.38s	remaining: 63.4ms
956:	learn: 0.1803922	total: 1.38s	remaining: 62ms
957:	learn: 0.1801767	total: 1.38s	remaining: 60.5ms
958:	learn: 0.1796219	total: 1.38s	remaining: 59.1ms
959:	learn: 0.1794796	total: 1.38s	remaining: 57.6ms
960:	learn: 0.1792958	total: 1.38s	remaining: 56.2ms
961:	learn: 0.1790849	total: 1.39s	remaining: 54.7ms
962:	learn: 0.1788734	total: 1.39s	remaining: 53.3ms
963:	learn: 0.1786708	total: 1.39s	remaining: 51.8ms
964:	learn: 0.1785048	total: 1.39s	remaining: 50.4ms
965:	learn: 0.1782705	total: 1.39s	remaining: 48.9ms
966:	learn: 0.1780874	total: 1.39s	remaining: 47.5ms
967:	learn: 0.1778538	total: 1.39s	remaining: 46.1ms
968:	learn: 0.1773931	total: 1.39s	remaining: 44.6ms
969:	learn: 0.1771249	total: 1.4s	remaining: 43.2ms
970:	learn: 0.1770137	total: 1.4s	remaining: 41.7ms
971:	learn: 0.1767534	total: 1.4s	remaining: 40.3ms
972:	learn: 0.1765513	total: 1.4s	remaining: 38.8ms
973:	learn: 0.1763886	total: 1.4s	remaining: 37.4ms
974:	learn: 0.1762021	total: 1.4s	remaining: 35.9ms
975:	learn: 0.1759060	total: 1.4s	remaining: 34.5ms
976:	learn: 0.1756775	total: 1.41s	remaining: 33.1ms
977:	learn: 0.1755569	total: 1.41s	remaining: 31.6ms
978:	learn: 0.1755497	total: 1.41s	remaining: 30.2ms
979:	learn: 0.1753609	total: 1.41s	remaining: 28.8ms
980:	learn: 0.1751724	total: 1.41s	remaining: 27.4ms
981:	learn: 0.1749744	total: 1.41s	remaining: 25.9ms
982:	learn: 0.1747493	total: 1.42s	remaining: 24.5ms
983:	learn: 0.1745655	total: 1.42s	remaining: 23ms
984:	learn: 0.1742428	total: 1.42s	remaining: 21.6ms
985:	learn: 0.1739070	total: 1.42s	remaining: 20.1ms
986:	learn: 0.1738763	total: 1.42s	remaining: 18.7ms
987:	learn: 0.1735653	total: 1.42s	remaining: 17.3ms
988:	learn: 0.1734413	total: 1.42s	remaining: 15.8ms
989:	learn: 0.1732562	total: 1.43s	remaining: 14.4ms
990:	learn: 0.1730306	total: 1.43s	remaining: 13ms
991:	learn: 0.1728261	total: 1.43s	remaining: 11.5ms
992:	learn: 0.1726228	total: 1.43s	remaining: 10.1ms
993:	learn: 0.1723789	total: 1.43s	remaining: 8.65ms
994:	learn: 0.1723525	total: 1.43s	remaining: 7.21ms
995:	learn: 0.1721074	total: 1.44s	remaining: 5.77ms
996:	learn: 0.1719336	total: 1.44s	remaining: 4.33ms
997:	learn: 0.1717171	total: 1.44s	remaining: 2.88ms
998:	learn: 0.1715751	total: 1.44s	remaining: 1.44ms
999:	learn: 0.1713438	total: 1.44s	remaining: 0us

## Eval Metrics

In [54]:
models=[linear,ridge,lasso,enet,knn,ada,svm,mlpc,dtc,rf,xgb,gbm,lgb,catbost]

# For train;
def ML(y,models):
    r2_score=models.score(X_train_scaled, y_train)
    return r2_score
for i in models:
    print(i,"Algorithm succed rate :", ML("survived",i))

LinearRegression() Algorithm succed rate : 0.8886517300804564
Ridge() Algorithm succed rate : 0.8279940941365418
Lasso() Algorithm succed rate : 0.1444873504727131
ElasticNet() Algorithm succed rate : 0.20082521592084923
KNeighborsRegressor() Algorithm succed rate : 0.857362402680176
AdaBoostRegressor() Algorithm succed rate : 0.9707788675850607
SVR() Algorithm succed rate : 0.610690444665906
MLPRegressor() Algorithm succed rate : 0.643878748188345
DecisionTreeRegressor() Algorithm succed rate : 1.0
RandomForestRegressor() Algorithm succed rate : 0.9837945570263724
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...) Algorithm succed rate : 0.9999940752826761
GradientBoostingRegressor() Algorithm succed rate : 0.9961708835802572
LGBMRegressor() Algorithm succed rate : 0.8852559991525166
<catboost.core.CatBoostRegressor object at 0x000001B82344A5F0> Algorithm succed rate : 0.9988894867605046

In [55]:
# For test;
def ML(y,models):
    r2_score=models.score(X_test_scaled, y_test)
    return r2_score
for i in models:
    print(i,"Algorithm succed rate :", ML("survived",i))

LinearRegression() Algorithm succed rate : 0.8489813024899066
Ridge() Algorithm succed rate : 0.7837567859000829
Lasso() Algorithm succed rate : 0.1624615665269098
ElasticNet() Algorithm succed rate : 0.22033692156322826
KNeighborsRegressor() Algorithm succed rate : 0.920822980791902
AdaBoostRegressor() Algorithm succed rate : 0.9282008766021559
SVR() Algorithm succed rate : 0.6970730951191091
MLPRegressor() Algorithm succed rate : 0.6366540640978883
DecisionTreeRegressor() Algorithm succed rate : 0.9436464890035525
RandomForestRegressor() Algorithm succed rate : 0.9595271183412645
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...) Algorithm succed rate : 0.9568915872872449
GradientBoostingRegressor() Algorithm succed rate : 0.9675343189514148
LGBMRegressor() Algorithm succed rate : 0.8779642617161398
<catboost.core.CatBoostRegressor object at 0x000001B82344A5F0> Algorithm succed rate : 0.9656835855144517

* You can choose best models and apply hyperparameter tuning.

* Using best hyperparameters nd all data, you can obtain final model, and save the final model.

# Hyperparameter Tuning

# Final Model

## Save the Final Model

In [ ]:
# TASK DONE!!!!!!!